FROM oven/bun:latest

WORKDIR /app

# COPY --chmod=0755 entrypoint.sh /entrypoint.sh

COPY package.json bun.lockb ./
RUN bun install
COPY . .
RUN bunx prisma generate

EXPOSE 4000

ENV NODE_ENV=development

ENTRYPOINT ["bun","run","dev"]